name: Nightly Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions: write-all

concurrency:
  group: "${{ github.workflow }} - ${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          save-if: true
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm run prebuild ${{ matrix.target }}
      - uses: tauri-apps/tauri-action@v0
        env:
          NODE_OPTIONS: "--max_old_space_size=6144"
          APPLE_SIGNING_IDENTITY: "-"
          VITE_BUILD_VERSION: "${{ github.run_number }}"
        with:
          tauriScript: pnpm
          args: --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: nightly-${{ matrix.target }}
          path: |
            src-tauri/target/${{ matrix.target }}/release/bundle/**

