name: 配额超限订阅删除功能 - 测试构建

on:
  workflow_dispatch:
  push:
    branches:
      - fix/batch-import-preview
    paths:
      - 'src/**'
      - 'src-tauri/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/test-build.yml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'src/**'
      - 'src-tauri/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/test-build.yml'

permissions: write-all

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  build-quota-feature:
    name: 构建配额删除功能
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies (macOS only)
        if: runner.os == 'macOS'
        run: |
          brew install openssl@3 pkg-config
          OPENSSL_DIR=$(brew --prefix openssl@3)
          echo "OPENSSL_DIR=$OPENSSL_DIR" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$OPENSSL_DIR/lib" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=$OPENSSL_DIR/include" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Download mihomo binaries
        run: pnpm prebuild

      - name: Build the app
        run: VITE_BUILD_VERSION="${{ github.run_number }}" pnpm tauri build --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=4096
          # 使用ad-hoc签名，减少macOS安全阻拦
          APPLE_SIGNING_IDENTITY: "-"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clash-verge-配额删除功能-${{ runner.os }}-${{ github.run_number }}
          path: |
            src-tauri/target/release/bundle
          retention-days: 3