name: Windows 个人构建

on:
  workflow_dispatch:
  push:
    branches: [dev]
    paths:
      - 'src/**'
      - 'src-tauri/**'
      - '.github/workflows/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'vite.config.mts'
      - 'tsconfig.json'

permissions: write-all

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

concurrency:
  group: "windows-personal-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-windows-x64:
    name: Build Windows (x64)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install frontend deps
        run: pnpm install --frozen-lockfile

      - name: Download sidecar binaries (x64)
        run: pnpm run prebuild x86_64-pc-windows-msvc

      - name: Create Tauri config override (disable updater)
        shell: pwsh
        run: |
          $config = @'
          {
            "$schema": "../node_modules/@tauri-apps/cli/config.schema.json",
            "plugins": {
              "updater": {
                "dialog": false,
                "endpoints": []
              }
            },
            "bundle": {
              "windows": {
                "nsis": {}
              }
            }
          }
          '@
          $config | Out-File -FilePath "src-tauri/tauri.personal.conf.json" -Encoding UTF8

      - name: Build app (x64 NSIS)
        uses: tauri-apps/tauri-action@v0
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: pnpm
          args: --target x86_64-pc-windows-msvc -b nsis --config src-tauri/tauri.personal.conf.json

      - name: List artifacts
        shell: pwsh
        run: |
          Get-ChildItem -Path "src-tauri/target/" -Recurse -Include "*.exe", "*.msi" | Select-Object FullName

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clash-verge-windows-x64-${{ github.sha }}-${{ github.run_number }}
          path: |
            src-tauri/target/x86_64-pc-windows-msvc/release/bundle/nsis/*.exe
            src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/*.msi
          if-no-files-found: warn
          retention-days: 7

